import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ActiveLink } from "@/ui/atoms/ActiveLink";
import { AppRoutes } from "@/types/app-routes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="bg-white">
					<div className="mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-24 lg:max-w-7xl lg:px-8">
						<nav className="mb-10">
							<ul className="flex justify-center space-x-4">
								<li>
									<ActiveLink
										href={AppRoutes.HOME}
										className="px-4 py-2 text-lg"
									>
										Home
									</ActiveLink>
								</li>
								<li>
									<ActiveLink
										exact={true}
										href={`${AppRoutes.PRODUCTS}`}
										className="px-4 py-2 text-lg"
									>
										Products
									</ActiveLink>
								</li>
							</ul>
						</nav>
						{children}
					</div>
				</div>
			</body>
		</html>
	);
}
